language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: afyWSXS/K66kKRzRusXxOjzvFPRGBtW+H7zSegYxNglDtx1SpMg7m491w0avBHgxYYArrCrTZS62tW6BB5F6wcLmYlJ97ctAzcR6htwAfGsxOnKXzBlvLa4UtLcbj4N89jdKv5RY6YnbOJ/nJoi7/UGFXxTrot5yX0AV56tWGkr7iLxJqAVz9ojEpTjS8sgkHzq7qJ7cylAmZUTWoUt/qptOOmVV2H4BDQbw+t3/Y7yHCeDRt5Svc0b/TuQBTu8WF8o/XGOSdUhvZcI8HGyqBYu2MvhwoLmRDDjbIZ3EmH5B8jjOyYaJvJxRVT4Vi8a6cbIGW6PFLdPNKPmS9E6c3eudZgkb/rmjiLW8MaJTZWPaetvr4L5NvecW7IYSmHPhkFQMvrkGs9/slkzeAt0YxWJL07GMx5EjIbA3J+UCQtMAlxSJHmFhuN9KOGXuRxU0TGtrFH0L0aTxsJ5S6wHhW+WGu6DD43ibpeLHWRRTIymxAmNgV++KJdWYOmD+AQKkCl89j95wt2mtOPPSOQARAFBmZox2q3lDc+yPCgbIW15P29WuTSSv0pWc7Vhsr+zCrf6na+xpPC0x6MqTCfvtv7WQTXM+ssxJwJWxo0KPxhW1qcP6ZsEOx+T4x1vOAtc8JA2CpQ3Ty5ETcHBiJSVMMGeO23hbOwLFigiuVh84L6U=
  - secure: bnb1HNUAgKBuYv1Bu3qw4o+p/RZ9MER/aPIJzQue1LepiywItXrOVmlKqNCPyueGVCC0eR5FDE59+iBTO7Qw647+aYZ/j8fWowT0h5Jwg1tk0QFIBp8lGzM18oUHfJ0DVQYw5q+ogukiV6oXCbmmh0lxZZrTnpYVFPVTHuC+fybyyuWUgvnfW2dTBhJCn9uUackj0Gnl6NZkNBYAjRABKJVNsODRh7rw4MGlS33HStIZ93H50uVgNgnXR25F8CJIKbRrcKfwAV2If9UPLZw1cGW6nyEywt9426nVLAoaaj21vG7TNjHNsHGNO+BMP3dAIgXUNylG+k1S34X05PPIF7ibyNzGOS4XSrDIJYkAcOAsKBvnMsYoyihvyx/EGc1HCI8NrQgbWg4O9gEA6Micc1O6ZuUdeb3HB47Iw03zcW7VlXCVwd/GOrneAVW+SGxMdKyRQRL6HL0sCkgnwa7tcZYMWw1JlQZdIsEuMxaMtCrCbWpjv5cosM1r989jQkdyNC8wdxa/zODWQO15Y81w3yqDN345WxLWHh5aYwyRGLgYK5/vZnO2YtqvEOMcTXQ0tXShyFzjX+ygy0QPCyWEp7b31lWa0s6AQN5Kz1AOr3kA25P+exvZUeHZSQwOhp3JCEvXXOO1ZpLgyewsYu0gpQvEXMSrmralpyK/ViYMbSc=
