language: node_js
node_js:
- 0.10.25
install:
- rm -rf node_modules
- rm -rf bower_components
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp clean
- gulp preprocessors
- gulp test
- gulp useref
- gulp copy-files
sudo: false
after_success:
- gulp coveralls
